# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WisHope' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for WisHope
  pod 'MaterialComponents/BottomSheet'
  pod 'NBBottomSheet', '~> 1.2'
  pod 'TwilioVideo', '~> 3.2'
  # Add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'

  # Add the pods for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Core'
  pod 'Firebase/Functions'
  pod 'Firebase/Messaging'
  target 'WisHopeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WisHopeUITests' do
    # Pods for testing
  end

end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if Gem::Version.new('9.0') > Gem::Version.new(config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'])
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
  end
end
